services:
  kiwicard-server:
    image: teamj/kiwicard-spring-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - BANK_WITH_PORT=wiremock-bank:9090
      - CARD_WITH_PORT=wiremock-card:9091
      - HAPPYKIDS_WITH_PORT=wiremock-happykids:9092
      - POSTGRES_HOST=postgres:5432
    entrypoint: "java -jar /opt/app/app.jar --bank.host.baseurl=http://$${BANK_WITH_PORT} --cardeditor.host.baseurl=http://$${CARD_WITH_PORT} --happykids.host.baseurl=http://$${HAPPYKIDS_WITH_PORT}"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --silent --fail localhost:8080/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:17.2
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=kiwicard-db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d kiwicard-db -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  # A simple java CLI
  kiwicard-cli:
    image: teamj/kiwicard-spring-cli
    container_name: cli
    environment:
      - SERVER_WITH_PORT=kiwicard-server:8080
    entrypoint: "java -jar /opt/app/app.jar"
    depends_on:
      kiwicard-server:
        condition: service_healthy
    volumes:
      - ./cli/demo.txt:/opt/app/demo.txt
    stdin_open: true
    tty: true
    healthcheck:
      test: "curl --silent --fail localhost:8081/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  wiremock-bank:
    image: wiremock/wiremock:3.12.0
    container_name: wiremock-bank
    ports:
      - "9090:8080"
    volumes:
      - ./external/bank/mappings:/home/wiremock/mappings
      - ./external/bank/__files:/home/wiremock/__files
    command: "--verbose --global-response-templating"
    restart: always

  wiremock-card:
    image: wiremock/wiremock:3.12.0
    container_name: wiremock-card
    ports:
      - "9091:8080"
    volumes:
      - ./external/card/mappings:/home/wiremock/mappings
      - ./external/card/__files:/home/wiremock/__files
    command: "--verbose --global-response-templating"
    restart: always

  wiremock-happykids:
    image: wiremock/wiremock:3.12.0
    container_name: wiremock-happykids
    ports:
      - "9092:8080"
    volumes:
      - ./external/happykids/mappings:/home/wiremock/mappings
      - ./external/happykids/__files:/home/wiremock/__files
    command: "--verbose --global-response-templating"
    restart: always
